---
title: "Project 2"
author: "Kate Sheafor and Amy Portillo-Ramirez"
date: "11/08/2021"
output: html_document
---
Conditionals
  If less than X ratings
Loop
  Colors
Function
  No :)
  
```{r}
library(ggplot2)
books<- read.csv("books.csv")
books$num_pages <- as.numeric(books$num_pages)
books$average_rating <- as.numeric(books$average_rating)
```

original code
```{r}
ggplot(books, aes(x= average_rating)) + geom_histogram(stat="bin", binwidth = 0.05, fill="cornflowerblue",color="black") + xlab("Average Rating (0-5)") + ylab("Number of Ratings (millions)")
```

assigning colors og
```{r}
colors <- c(0:5)

assign.colors <- function(color.in){
colors.as.numbers <- switch(color.in,
  "red" = r,
  "yellow"= y,
  "green"= g
  )
return(assign.colors)
}
```


#colors: ave rating <2 red
       2.5-3.5=yellow
        3.6-5 green
if else as conditional (nested)
for loop with conditional
red<-books$average_rating[0:2.5]
yellow<-books$average_rating[2.6:3.5]
green<-books$average_rating[3.6:5]

function(graphcolor){
if(books$average_rating[0:2.5] == "last") 
  color==red
} else (average == "average", ,) {
  color==yellow
} else {
  color==green
```{r}
library(ggplot2)
r<-books$average_rating<=2.5
y<-books$average_rating>2.5
g<-books$average_rating>4
rating <- c("last", "average", "first")
###function###

###conditional###
x<-books$average_rating
graphcolor <- function(x) {
  if (x=="last") 
    output <- color==red
    } else if (x=="average"){
               color==yellow
    }else if (x=="good"){
               output <-color==green
      }
  (output)=color
###GRAPH###
ggplot(books, aes_string(x= books$average_rating<2.6)) + geom_histogram(stat = "bin", binwidth = 0.05 , fill="cornflowerblue",color="black") + xlab("Average Rating (0-5)") + ylab("Number of Ratings (millions)")
```


omit all ratings 100,000,000>
```{r}
ggplot(books, aes(x= average_rating)) + geom_histogram(stat="bin", binwidth = 0.05, fill="cornflowerblue",color="black") + xlab("Average Rating (0-5)") + ylab("Number of Ratings (millions)")


```

